import { test, expect } from '@playwright/test';

test('3D journey, inspection, pause, seek, speed, settings and looping', async ({ page }) => {
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('./');
  await expect(page.locator('#scene canvas')).toBeVisible();
  await expect(page.locator('#loading')).toHaveCount(0);
  await page.locator('#restart').click();
  await page.locator('#play').click();
  await page.waitForTimeout(550);
  await page.locator('#play').click();
  const paused = await page.locator('#timeline').inputValue();
  await page.waitForTimeout(400);
  expect(await page.locator('#timeline').inputValue()).toBe(paused);
  for (let i=0;i<6;i++) {
    await page.locator(`[data-stage="${i}"]`).click();
    await expect(page.locator(`[data-stage="${i}"]`)).toHaveAttribute('aria-current','step');
    await expect(page.locator('#detail-step')).toHaveText(`ขั้นตอนที่ ${String(i+1).padStart(2,'0')}`);
    await page.locator('#more-detail').click();
    await expect(page.locator('#details-dialog')).toBeVisible();
    await page.locator('#details-dialog .close-dialog').click();
  }
  await expect(page.locator('#altitude')).toHaveText('0.0');
  await expect(page.locator('#cycle-count')).toHaveText('3');
  await page.locator('#timeline').evaluate(el => { el.value='37';el.dispatchEvent(new Event('input',{bubbles:true})); });
  await expect(page.locator('[data-stage="2"]')).toHaveAttribute('aria-current','step');
  await page.locator('#cutaway').click();
  await expect(page.locator('#cutaway')).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('.cutaway-label')).toBeVisible();
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  const canvas = page.locator('#scene canvas');
  const bounds = await canvas.boundingBox();
  const cameraBefore = await page.locator('#label-hail').getAttribute('style');
  await page.mouse.move(bounds.x+bounds.width*0.5,bounds.y+bounds.height*0.5);
  await page.mouse.down();
  await page.mouse.move(bounds.x+bounds.width*0.6,bounds.y+bounds.height*0.5,{steps:5});
  await page.mouse.up();
  await page.waitForTimeout(400);
  expect(await page.locator('#label-hail').getAttribute('style')).not.toBe(cameraBefore);
  await page.locator('#reset-camera').click();
  await page.locator('#fullscreen').click();
  await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true);
  await page.locator('#fullscreen').click();
  await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(false);
  await page.locator('#cycles').evaluate(el=>{el.value='6';el.dispatchEvent(new Event('input',{bubbles:true}));});
  await expect(page.locator('#cycle-total')).toHaveText('6');
  await expect(page.locator('#cycles-value')).toHaveText('6');
  await page.locator('#updraft').evaluate(el=>{el.value='150';el.dispatchEvent(new Event('input',{bubbles:true}));});
  await expect(page.locator('#updraft-value')).toHaveText('150');
  await page.locator('#restart').click();
  await page.locator('#speed').selectOption('8');
  await page.locator('#play').click();
  await page.waitForTimeout(600);
  await page.locator('#play').click();
  expect(Number(await page.locator('#timeline').inputValue())).toBeGreaterThan(2);
  // One shot must stop at the ground; continuous looping must return to the first stage.
  await page.locator('#loop').click();
  await expect(page.locator('#loop')).toHaveAttribute('aria-pressed','false');
  await page.locator('#timeline').evaluate(el=>{el.value=String(Number(el.max)-0.3);el.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.locator('#play').click();
  await expect(page.locator('#playing-label')).toHaveText('ครบวงจรแล้ว');
  await expect(page.locator('#altitude')).toHaveText('0.0');
  await page.locator('#loop').click();
  await page.locator('#timeline').evaluate(el=>{el.value=String(Number(el.max)-0.3);el.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.locator('#play').click();
  await expect(page.locator('[data-stage="0"]')).toHaveAttribute('aria-current','step');
  await page.locator('#play').click();
  await page.locator('#about').click();
  await expect(page.locator('#about-dialog')).toBeVisible();
  await expect(page.locator('#about-dialog a[href$="reference.jpg"]')).toBeVisible();
  await page.locator('#about-dialog .close-dialog').click();
  await page.locator('#show-clouds').uncheck();
  await page.locator('#show-flow').uncheck();
  await page.locator('#show-labels').uncheck();
  await expect(page.locator('#atmosphere-labels')).toBeHidden();
  expect(errors).toEqual([]);
});

test('mobile fits and every step can be opened', async ({page}) => {
  await page.setViewportSize({width:390,height:844});
  await page.goto('./');
  await expect(page.locator('#scene canvas')).toBeVisible();
  await page.locator('[data-stage="3"]').click();
  await page.locator('#cutaway').click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.locator('#more-detail').click();
  await expect(page.locator('#details-dialog')).toBeVisible();
  await expect(page.locator('.ice-explainer')).toBeVisible();
  await page.locator('#details-dialog .close-dialog').click();
  await page.screenshot({path:'test-results/mobile.png',fullPage:true});
});
